name: Build and Analyze with SonarCloud

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Install dependencies
        run: dotnet restore PE_PRN231_FA24_TrialTest_TranDucManh_BE.sln

      - name: Build
        run: dotnet build PE_PRN231_FA24_TrialTest_TranDucManh_BE.sln --no-restore --configuration Release

      - name: Test
        run: dotnet test PE_PRN231_FA24_TrialTest_TranDucManh_BE.sln --no-build --configuration Release

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
